/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type OpenGraphImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type AboutMeButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type CurrentFocusProject = {
  project: ProjectReference
  button?: ProjectButton
}

export type ProjectButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type ProjectsShowcaseButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type CertificatesGalleryButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type PrimaryButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type SecondaryButton = {
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type Locale = {
  _id: string
  _type: 'locale'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  tag: string
  isDefault?: boolean
}

export type TechnologyReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'technology'
}

export type TechnologyReference_2 = {
  _type: 'technologyReference'
  technology: TechnologyReference
}

export type ProjectReference_2 = {
  _type: 'projectReference'
  project: ProjectReference
  overrideLabel?: string
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  keywords?: string
  openGraphImage?: OpenGraphImage
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Header = {
  _type: 'header'
  menuItems?: Array<
    {
      _key: string
    } & PageReference
  >
}

export type Footer = {
  _type: 'footer'
  menuItems?: Array<
    {
      _key: string
    } & PageReference
  >
}

export type CertificateReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'certificate'
}

export type CertificateReference_2 = {
  _type: 'certificateReference'
  certificate: CertificateReference
}

export type Button = {
  _type: 'button'
  buttonText?: string
  isExternalLink?: boolean
  isDownload?: boolean
  buttonLink?: string
}

export type TechnologiesOverview = {
  _type: 'technologiesOverview'
  heading: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  groups?: Array<{
    label?: string
    technologies?: Array<
      {
        _key: string
      } & TechnologyReference_2
    >
    _type: 'group'
    _key: string
  }>
}

export type TechnologiesStack = {
  _type: 'technologiesStack'
  technologies?: Array<
    {
      _key: string
    } & TechnologyReference_2
  >
}

export type Subhero = {
  _type: 'subhero'
  eyebrow?: string
  heading: string
  highlightLine?: boolean
}

export type RichTextSection = {
  _type: 'richTextSection'
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type ProjectsShowcase = {
  _type: 'projectsShowcase'
  eyebrow?: string
  heading?: string
  button?: ProjectsShowcaseButton
  projects?: Array<
    {
      _key: string
    } & ProjectReference_2
  >
}

export type Highlights = {
  _type: 'highlights'
  eyebrow?: string
  heading: string
  items?: Array<{
    value: string
    label: string
    description?: string
    _type: 'item'
    _key: string
  }>
}

export type Hero = {
  _type: 'hero'
  headline: string
  subheadline?: Array<{
    text: string
    _type: 'item'
    _key: string
  }>
  portraitImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  mobileImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ExperienceTimeline = {
  _type: 'experienceTimeline'
  eyebrow?: string
  heading: string
  entries?: Array<{
    period?: string
    company: string
    role?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies?: Array<
      {
        _key: string
      } & TechnologyReference_2
    >
    logo?: Logo
    _type: 'entry'
    _key: string
  }>
}

export type CurrentFocus = {
  _type: 'currentFocus'
  heading: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  project?: CurrentFocusProject
}

export type ContactCta = {
  _type: 'contactCta'
  eyebrow?: string
  heading: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  primaryButton?: PrimaryButton
  secondaryButton?: SecondaryButton
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type CertificatesGrid = {
  _type: 'certificatesGrid'
  eyebrow?: string
  heading?: string
  certificates?: Array<
    {
      _key: string
    } & CertificateReference_2
  >
}

export type CertificatesGallery = {
  _type: 'certificatesGallery'
  eyebrow?: string
  heading: string
  button?: CertificatesGalleryButton
  certificates?: Array<
    {
      _key: string
    } & CertificateReference_2
  >
}

export type AboutMe = {
  _type: 'aboutMe'
  eyebrow?: string
  heading: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  button?: AboutMeButton
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type AboutBanner = {
  _type: 'aboutBanner'
  title?: string
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type GlobalReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'global'
}

export type ArticlesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articles'
}

export type CategoriesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'categories'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | PageReference
    | GlobalReference
    | ProjectReference
    | CertificateReference
    | TechnologyReference
    | ArticlesReference
    | CategoriesReference
  language: string
}

export type Categories = {
  _id: string
  _type: 'categories'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
}

export type Articles = {
  _id: string
  _type: 'articles'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  title: string
  readTime?: number
  slug: Slug
  publishedAt: string
  articlesTags: Array<
    {
      _key: string
    } & CategoriesReference
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    keywords?: string
    openGraphImage?: OpenGraphImage
  }
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Technology = {
  _id: string
  _type: 'technology'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  name: string
  svg?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Certificate = {
  _id: string
  _type: 'certificate'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
  slug: Slug
  issuer?: string
  issuedAt?: string
  certificateUrl?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  seo?: {
    metaTitle?: string
    metaDescription?: string
    keywords?: string
    openGraphImage?: OpenGraphImage
  }
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Global = {
  _id: string
  _type: 'global'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  header?: {
    menuItems?: Array<
      {
        _key: string
      } & PageReference
    >
  }
  footer?: {
    menuItems?: Array<
      {
        _key: string
      } & PageReference
    >
  }
  phone?: string
  email?: string
  linkedin?: string
  instagram?: string
  github?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title?: string
  slug?: Slug
  seo?: {
    metaTitle?: string
    metaDescription?: string
    keywords?: string
    openGraphImage?: OpenGraphImage
  }
  pageBuilder?: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & Subhero)
    | ({
        _key: string
      } & AboutBanner)
    | ({
        _key: string
      } & TechnologiesStack)
    | ({
        _key: string
      } & AboutMe)
    | ({
        _key: string
      } & ExperienceTimeline)
    | ({
        _key: string
      } & Highlights)
    | ({
        _key: string
      } & TechnologiesOverview)
    | ({
        _key: string
      } & CurrentFocus)
    | ({
        _key: string
      } & ProjectsShowcase)
    | ({
        _key: string
      } & RichTextSection)
    | ({
        _key: string
      } & CertificatesGallery)
    | ({
        _key: string
      } & CertificatesGrid)
    | ({
        _key: string
      } & ContactCta)
  >
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  category?: 'done' | 'going'
  title: string
  slug: Slug
  description?: string
  projectUrl?: string
  technologies?: Array<
    {
      _key: string
    } & TechnologyReference_2
  >
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  seo?: {
    metaTitle?: string
    metaDescription?: string
    keywords?: string
    openGraphImage?: OpenGraphImage
  }
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | OpenGraphImage
  | AboutMeButton
  | Logo
  | ProjectReference
  | CurrentFocusProject
  | ProjectButton
  | ProjectsShowcaseButton
  | CertificatesGalleryButton
  | PrimaryButton
  | SecondaryButton
  | Locale
  | TechnologyReference
  | TechnologyReference_2
  | ProjectReference_2
  | Seo
  | PageReference
  | Header
  | Footer
  | CertificateReference
  | CertificateReference_2
  | Button
  | TechnologiesOverview
  | TechnologiesStack
  | Subhero
  | RichTextSection
  | ProjectsShowcase
  | Highlights
  | Hero
  | ExperienceTimeline
  | CurrentFocus
  | ContactCta
  | CertificatesGrid
  | CertificatesGallery
  | AboutMe
  | AboutBanner
  | TranslationMetadata
  | InternationalizedArrayReference
  | GlobalReference
  | ArticlesReference
  | CategoriesReference
  | InternationalizedArrayReferenceValue
  | Categories
  | Articles
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | Technology
  | Certificate
  | Global
  | Page
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
